---
title: "AppCosteo Resumen de Resultados"
output: 
  word_document: default
  pdf_document: default
date: "`r Sys.Date()`"
header-includes:
  - \usepackage{titling}
  - \usepackage{pdflscape}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \usepackage{multirow}
  - \usepackage{tabu}
params:
  title: ""
  author: ""
  actors: ""
  notes: ""
  summary_dat: NA
  plot1: NA
  plot2: NA
  plot3: NA
always_allow_html: true
---

```{r include=F}
# The `dat` object is a reactiveValues() object (list) with the following items: summary_table, plot1, plot2, plot3 
library(tidyverse)
library(kableExtra)
library(flextable)

set_flextable_defaults(
  font.size = 8, font.family = "Helvetica",
  table.layout = "autofit",
  border.color = "black",
  padding.top = 2, padding.bottom = 2,
  padding.left = 2, padding.right = 2)

```

**Título del proyecto:** `r params$title`

**Autor del proyecto:** `r params$author`

**Actores:** `r params$actors`

**Notas:** `r params$notes`

\newpage

# Presupuesto por fases

```{r, echo = F, message = F, warning=FALSE}
if(nrow(params$summary_dat) > 0){
d1 <- params$summary_dat %>%
  group_by(section, fase) %>%
  summarize(`Fase Duracion (meses)` = unique(fase_duracion),
            `Total ($)` = format(sum(total, na.rm = T), big.mark = ",")) %>%
  ungroup() %>%
  rename(`Intervención` = section, Fase = fase)

d1 <- flextable(d1) %>%
  merge_v(j = ~ `Intervención` + Fase) %>%
  theme_booktabs(bold_header = T) %>%
  align(align = "center", part = "all") %>%
  autofit(add_w = 0.2)

d1
}
```

```{r plot_1, echo=F, fig.align='left'}
if(!is.null(params$plot1)){
  params$plot1
}
```

\newpage

# Presupuesto por conceptos

```{r, echo=F, message=F, warning=F}
if(nrow(params$summary_dat) > 0){
d2 <- params$summary_dat %>%
  group_by(section, concepto, fase) %>%
  summarize(`Actividades` = n_distinct(actividad),
            `Total ($)` = format(sum(total, na.rm = T), big.mark = ",")) %>%
  ungroup() %>%
  rename(`Intervención` = section, Concepto = concepto, Fase = fase)

d2 <- flextable(d2) %>%
  merge_v(j = ~ `Intervención` + Concepto + Fase) %>%
  theme_booktabs(bold_header = T) %>%
  align(align = "center", part = "all") %>%
  autofit(add_w = 0.2)

d2
}
```

```{r, echo=F, fig.align='left'}
if(!is.null(params$plot2)){
  params$plot2
}
```

\newpage

# Presupuesto por actores

```{r, echo=F, message=F, warning=F}
if(nrow(params$summary_dat) > 0){
d3 <- params$summary_dat %>%
  group_by(responsable, fase) %>%
  summarize(`Actividades` = n_distinct(actividad),
            `Total ($)` = format(sum(total, na.rm = T), big.mark = ",")) %>%
  ungroup() %>%
  rename(Responsable = responsable, Fase = fase)

d3 <- flextable(d3) %>%
  merge_v(j = ~ Responsable + Fase) %>%
  theme_booktabs(bold_header = T) %>%
  align(align = "center", part = "all") %>%
  autofit(add_w = 0.2)

d3
}
```

```{r, echo=F, fig.align='left'}
if(!is.null(params$plot3)){
  params$plot3
}
```

\newpage

\blandscape

# Presupuesto extendido

```{r, echo=F, message=F, warning=F}
if(nrow(params$summary_dat)){
  
d4 <- params$summary_dat %>%
  group_by(section, fase, subfase, actividad, responsable) %>%
  summarize(`Total ($)` = format(sum(total, na.rm = T), big.mark = ",")) %>%
  ungroup() %>%
  rename(Programa = section, Fase = fase, Subfase = subfase, Actividad = actividad, Responsable = responsable)

d4 <- flextable(d4) %>%
  merge_v(j = ~ Programa + Fase + Subfase) %>%
  theme_booktabs(bold_header = T) %>%
  align(align = "center", part = "all") %>%
  autofit(add_w = 0.2)

d4
}
```

\elandscape
